FinDocs/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'FinDocs' # namespace

urlpatterns = [
    # Doc
    path('', views.DocListView.as_view(), name='index'), # 検索
    path('add/', login_required(views.DocCreateView.as_view()), name='add'), # 追加
    path('<int:pk>/detail/', views.DocDetailView.as_view(), name='detail'), # 詳細
    path('<int:pk>/edit/', login_required(views.DocEditView.as_view()), name='edit'), # 編集
    path('<int:pk>/del/', login_required(views.DocDeleteView.as_view()), name='del'), # 削除
    # DocType
    path('category/', login_required(views.DocTypeListView.as_view()), name='category_index'), # 検索
    path('category/add/', login_required(views.DocTypeCreateView.as_view()), name='category_add'), # 検索
    path('category/<int:pk>/edit/', login_required(views.DocTypeEditView.as_view()), name='category_edit'), # 編集
    path('category/<int:pk>/del/', login_required(views.DocTypeDeleteView.as_view()), name='category_del'), # 削除
    # Contact
    path('contact/', login_required(views.ContactListView.as_view()), name='contact_index'), # 検索
    path('contact/add/', login_required(views.ContactCreateView.as_view()), name='contact_add'), # 検索
    path('contact/<int:pk>/edit/', login_required(views.ContactEditView.as_view()), name='contact_edit'), # 編集
    path('contact/<int:pk>/del/', login_required(views.ContactDeleteView.as_view()), name='contact_del'), # 削除
    # DocType
    path('docplace/', login_required(views.OriginalDocPlaceListView.as_view()), name='docplace_index'), # 検索
    path('docplace/add', login_required(views.OriginalDocPlaceCreateView.as_view()), name='docplace_add'), # 検索
    path('docplace/<int:pk>/edit/', login_required(views.OriginalDocPlaceEditView.as_view()), name='docplace_edit'), # 編集
    path('docplace/<int:pk>/del/', login_required(views.OriginalDocPlaceDeleteView.as_view()), name='docplace_del'), # 削除
    # Import/Export
    path('import/', login_required(views.DataImport.as_view()), name='import'), # インポート
    path('export/', login_required(views.DataExport), name='export'), # エクスポート
]

core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/home', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', include('FinDocs.urls')),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
{% block extra_css %}{% endblock %}
<title>KOMUGI Toolbox</title>
</head>

<body style="padding-bottom:50px;">
<!-- top navi -->
<nav class="navbar navbar-expand navbar-dark bg-dark sticky-top mb-4">
  <span class="navbar-brand h1">KOMUGI Toolbox</span>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link active" href="{% url 'FinDocs:index' %}">FinDocs</a>
      </li>
    </ul>

    <ul class="navbar-nav">
      <li class="nav-item">
        {% if user.is_authenticated %}
        <div class="dropdown">
          <a href="#" class="dropdown-toggle nav-link active"
              id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ user.email }}
          </a>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            {% block app_navi_item %}
            {% endblock %}
            <a class="dropdown-item" href="{% url 'logout' %}">ログアウト</a>
          </div>
        </div>
        {% else %}
        <a class="nav-link active" href="{% url 'login' %}">ログイン</a>
        {% endif %}
      </li>
    </ul>
  </div>
</nav>

<!-- main contents -->
<main>
  <div class="container">
  {% block content %}
  {% endblock %}
  </div>
</main>

<!-- bottom navi -->
<nav class="navbar navbar-expand navbar-dark bg-dark fixed-bottom">
  <div class="col text-right text-muted">
    <small>Copyright © NBRP KOMUGI All Rights Reserved.</small>
  </div>
</nav>

<!-- javascripts -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsbarcode/3.11.0/JsBarcode.all.min.js" integrity="sha256-BjqnfACYltVzhRtGNR2C4jB9NAN0WxxzECeje7/XpwE=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bs-custom-file-input/dist/bs-custom-file-input.js"></script>

<script>
  bsCustomFileInput.init();
</script>

{% block extra_js %}{% endblock %}

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}

<div class="row justify-content-center mt-5">
  <div class="col-lg-4 col-md-6 col-sm-8">
    <div class="card">
      <div class="card-body">
        <div class="mt-3">
          {% if user.is_authenticated %}
            <p><a href="{% url 'logout' %}">logout</a></p>
          {% else %}
            <a href="{% url 'login' %}">login</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}