FinDocs/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'FinDocs' # namespace

urlpatterns = [
    # Doc
    path('', views.DocListView.as_view(), name='index'), # 検索
    path('add/', login_required(views.DocCreateView.as_view()), name='add'), # 追加
    path('<int:pk>/detail/', views.DocDetailView.as_view(), name='detail'), # 詳細
    path('<int:pk>/edit/', login_required(views.DocEditView.as_view()), name='edit'), # 編集
    path('<int:pk>/del/', login_required(views.DocDeleteView.as_view()), name='del'), # 削除
    # DocType
    path('category/', login_required(views.DocTypeListView.as_view()), name='category_index'), # 検索
    path('category/add/', login_required(views.DocTypeCreateView.as_view()), name='category_add'), # 検索
    path('category/<int:pk>/edit/', login_required(views.DocTypeEditView.as_view()), name='category_edit'), # 編集
    path('category/<int:pk>/del/', login_required(views.DocTypeDeleteView.as_view()), name='category_del'), # 削除
    # Contact
    path('contact/', login_required(views.ContactListView.as_view()), name='contact_index'), # 検索
    path('contact/add/', login_required(views.ContactCreateView.as_view()), name='contact_add'), # 検索
    path('contact/<int:pk>/edit/', login_required(views.ContactEditView.as_view()), name='contact_edit'), # 編集
    path('contact/<int:pk>/del/', login_required(views.ContactDeleteView.as_view()), name='contact_del'), # 削除
    # DocType
    path('docplace/', login_required(views.OriginalDocPlaceListView.as_view()), name='docplace_index'), # 検索
    path('docplace/add', login_required(views.OriginalDocPlaceCreateView.as_view()), name='docplace_add'), # 検索
    path('docplace/<int:pk>/edit/', login_required(views.OriginalDocPlaceEditView.as_view()), name='docplace_edit'), # 編集
    path('docplace/<int:pk>/del/', login_required(views.OriginalDocPlaceDeleteView.as_view()), name='docplace_del'), # 削除
    # Import/Export
    path('import/', login_required(views.DataImport.as_view()), name='import'), # インポート
    path('export/', login_required(views.DataExport), name='export'), # エクスポート
]

core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/home', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', include('FinDocs.urls')),
]

FinDocs/models.py
from django.db import models
from django.core.validators import RegexValidator

class DocType(models.Model):
    """資料の種類"""
    name    = models.CharField('種類', max_length=100)
    priority= models.PositiveSmallIntegerField('優先度', null=True, blank=True)
    remarks = models.TextField('備考', blank=True)

    def __str__(self):
        return self.name

class Contact(models.Model):
    """資料の問合せ先"""
    contact_to = models.CharField('問合せ先', max_length=100)
    email      = models.EmailField('メールアドレス', max_length=254, null=True, blank=True)
    priority   = models.PositiveSmallIntegerField('優先度', null=True, blank=True)
    remarks    = models.TextField('備考', blank=True)

    def __str__(self):
        return self.contact_to

class OriginalDocPlace(models.Model):
    """原本の場所"""
    place    = models.CharField('場所名', max_length=255)
    priority = models.PositiveSmallIntegerField('優先度', null=True, blank=True)
    remarks  = models.TextField('備考', blank=True)

    def __str__(self):
        return self.place

class Doc(models.Model):
    public_or_not = ((0, '非公開'),(1, '公開'),)
    tel_number_regex = RegexValidator(regex=r'^[0-9]{8}$', message=("半角英数のみ"))

    """資料リスト"""
    title      = models.CharField('タイトル', max_length=80)
    type       = models.ForeignKey(DocType, verbose_name='種類', on_delete=models.SET_NULL, null=True, blank=True, default=1)
    content    = models.TextField('内容', blank=True)
    date       = models.DateField('作成年月日', blank=True, null=True)
    contact_to = models.ForeignKey(Contact, verbose_name='問合せ先', on_delete=models.SET_NULL, null=True, blank=True, default=1)
    is_public  = models.IntegerField(choices=public_or_not, verbose_name='公開状態', default=0)
    url        = models.URLField('資料URL', max_length=250, blank=True)
    image      = models.URLField('表紙URL', max_length=250, blank=True)
    barcode    = models.CharField('資料コード', max_length=8, blank=True, validators=[tel_number_regex], unique=False)
    original   = models.ForeignKey(OriginalDocPlace, verbose_name='原本所在', on_delete=models.SET_NULL, null=True, blank=True, default=1)
    backup     = models.CharField('バックアップファイル', max_length=250, blank=True)
    keywords   = models.TextField('キーワード', blank=True)
    created_at = models.DateField('登録日', auto_now_add=True)
    updated_at = models.DateField('更新日', auto_now=True)

    @property
    def get_year(self):
        if self.date:
            return self.date.strftime('%Y')

    def __str__(self):
        return self.title

FinDocs/forms.py
from django import forms

import re

from .models import *

class DocForm(forms.ModelForm):

    class Meta:
        model = Doc
        fields = (
            'title', 'type', 'content', 'date',
            'contact_to', 'is_public', 'url', 'image',
            'barcode', 'original', 'backup', 'keywords',
        )
        widgets = {
            'title'    : forms.TextInput(attrs={'size':'60'}),
            'content'  : forms.Textarea(attrs={'rows':4,'cols':60}),
            'date'     : forms.DateInput(attrs={"type":"date",'min':'1900-01-01','max':'2199-12-31'}),
            'url'      : forms.URLInput(attrs={'size':'60'}),
            'image'    : forms.URLInput(attrs={'size':'60'}),
            'backup'   : forms.TextInput(attrs={'size':'60'}),
            'keywords' : forms.Textarea(attrs={'rows':4,'cols':60}),
            # 'is_public': forms.RadioSelect(),
        }


class FilterForm(forms.ModelForm):
    keywords = forms.CharField(initial='', label='キーワード', required = False,)
    class Meta:
        model = Doc
        fields = ('type', 'date')

class DocTypeForm(forms.ModelForm):

    class Meta:
        model = DocType
        fields = ('name', 'priority', 'remarks')
        widgets={
            'name'    : forms.TextInput(attrs={'size':'60'}),
            'priority': forms.NumberInput(attrs={'min':'0'}),
            'remarks' : forms.Textarea(attrs={'rows':4,'cols':60}),
        }


class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = ('contact_to', 'email', 'priority', 'remarks')
        widgets={
            'contact_to': forms.TextInput(attrs={'size':'60'}),
            'email'     : forms.EmailInput(attrs={'size':'60'}),
            'priority': forms.NumberInput(attrs={'min':'0'}),
            'remarks' : forms.Textarea(attrs={'rows':4,'cols':60}),
        }

class OriginalDocPlaceForm(forms.ModelForm):

    class Meta:
        model = OriginalDocPlace
        fields = ('place', 'priority', 'remarks')
        widgets={
            'place'   : forms.TextInput(attrs={'size':'60'}),
            'priority': forms.NumberInput(attrs={'min':'0'}),
            'remarks' : forms.Textarea(attrs={'rows':4,'cols':60}),
        }

class DocUploadForm(forms.Form):
    name = forms.HiddenInput()

FinDocs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.utils import timezone
from django.db.models import Q
from django.core.paginator import Paginator
from django.core.exceptions import ValidationError
from django.views.generic import TemplateView, ListView, DetailView, UpdateView, CreateView, DeleteView, FormView
from django_pandas.io import read_frame
from django.views.decorators.http import require_POST

import os, io, csv, urllib
from functools import reduce
from operator import and_

from .models import *
from .forms import *

class DocListView(ListView):
    """検索＆一覧"""
    model = Doc
    template_name = 'FinDocs/index.html'
    context_object_name = 'recs'
    strict = False
    paginate_by = 10

    # クエリセット
    def get_queryset(self):
        if self.request.user.is_authenticated:
            if self.request.GET:
                cond_k = Q()
                cond_c = Q()
                cond_y = Q()
                if self.request.GET.get('k'):
                    words = self.request.GET.get('k').split()
                    cond_k = reduce(and_, [Q(title__icontains=w) | Q(content__icontains=w) | Q(barcode__icontains=w) | Q(keywords__icontains=w) for w in words])
                if self.request.GET.get('c'):
                    cond_c = Q(type__id=self.request.GET.get('c'))
                if self.request.GET.get('y'):
                    cond_y = Q(date__year=self.request.GET.get('y'))
                context = Doc.objects.filter(cond_k & cond_c & cond_y).order_by('-date', 'title', 'id') # 一覧（検索結果）
            else:
                context = Doc.objects.all().order_by('-date', 'title', 'id') # 一覧（全件）

        else:
            if self.request.GET:
                cond_k = Q()
                cond_c = Q()
                cond_y = Q()
                if self.request.GET.get('k'):
                    words = self.request.GET.get('k').split()
                    cond_k = reduce(and_, [Q(title__icontains=w) | Q(content__icontains=w) | Q(barcode__icontains=w) | Q(keywords__icontains=w) for w in words])
                if self.request.GET.get('c'):
                    cond_c = Q(type__id=self.request.GET.get('c'))
                if self.request.GET.get('y'):
                    cond_y = Q(date__year=self.request.GET.get('y'))
                context = Doc.objects.filter(Q(is_public=1) & cond_k & cond_c & cond_y).order_by('-date', 'title', 'id') # 一覧（検索結果）
            else:
                context = Doc.objects.filter(Q(is_public=1)).order_by('-date', 'title', 'id') # 一覧（全件）
        return context

    # その他のクエリセットなど
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # セレクトボックス「カテゴリ」
        context["cats"] = DocType.objects.all().order_by('priority', '-name',)
        # セレクトボックス「作成年」
        y_list = Doc.objects.all().dates('date', 'year', order='DESC')
        context["years"] = y_list.values_list('date__year', flat=True).distinct()

        if self.request.GET:
            if self.request.GET.get('k'):
                context["k"] = self.request.GET.get('k')
            if self.request.GET.get('c'):
                context["c"] = int(self.request.GET.get('c'))
            if self.request.GET.get('y'):
                context["y"] = int(self.request.GET.get('y'))
        return context

class DocDetailView(DetailView):
    """詳細"""
    model = Doc
    template_name = 'FinDocs/detail.html'
    context_object_name = 'rec'

class DocEditView(UpdateView):
    """編集"""
    model = Doc
    form_class = DocForm
    template_name = 'FinDocs/edit.html'
    context_object_name = 'rec'
    success_url = reverse_lazy('FinDocs:index')

    def form_valid(self, form):
        saved_rec = form.save()

        # バーコード付与
        if not saved_rec.barcode:
            saved_rec.barcode = "%03d%05d" %  (saved_rec.contact_to.pk, saved_rec.pk)
            saved_rec = form.save()

        # 「保存して詳細ページへ」
        if 'save_and_detail' in self.request.POST:
            return redirect('FinDocs:detail', pk=saved_rec.pk)
        # 「保存して編集を続ける」
        elif 'save_and_edit' in self.request.POST:
            return redirect('FinDocs:edit', pk=saved_rec.pk)
        # 「保存」
        return redirect('FinDocs:index')

    def form_isvalid(self, form):
        messages.error(self.request, '入力内容をご確認ください。')
        return super().form_invalid(form)


class DocCreateView(CreateView):
    """追加"""
    model = Doc
    form_class = DocForm
    template_name = 'FinDocs/add.html'
    context_object_name = 'rec'
    success_url = reverse_lazy('FinDocs:index')

    def form_valid(self, form):
        saved_rec = form.save()

        # バーコード付与
        if not saved_rec.barcode:
            saved_rec.barcode = "%03d%05d" %  (saved_rec.contact_to.pk, saved_rec.pk)
            saved_rec = form.save()

        # 「保存してもう一つ追加」
        if 'save_and_add' in self.request.POST:
            return redirect('FinDocs:add')
        # 「保存して編集を続ける」
        elif 'save_and_edit' in self.request.POST:
            return redirect('FinDocs:edit', pk=saved_rec.pk)
        # 「保存」
        return redirect('FinDocs:index')


class DocDeleteView(DeleteView):
    """削除"""
    model = Doc
    template_name = 'FinDocs/edit.html'
    context_object_name = 'rec'
    success_url = reverse_lazy('FinDocs:index')

#==============================

class DocTypeListView(ListView):
    """一覧"""
    model = DocType
    template_name = 'FinDocs/category_index.html'
    context_object_name = 'cats'
    strict = False

    # クエリセット
    def get_queryset(self):
        context = DocType.objects.all().order_by('priority') # 一覧（全件）
        return context


class DocTypeCreateView(CreateView):
    """追加"""
    model = DocType
    form_class = DocTypeForm
    template_name = 'FinDocs/category_add.html'
    context_object_name = 'cat'
    success_url = reverse_lazy('FinDocs:category_index')

    def form_valid(self, form):
        saved_cat = form.save()
        # 「保存」
        return redirect('FinDocs:category_index')


class DocTypeEditView(UpdateView):
    """編集"""
    model = DocType
    form_class = DocTypeForm
    template_name = 'FinDocs/category_edit.html'
    context_object_name = 'cat'
    success_url = reverse_lazy('FinDocs:category_index')

    def form_valid(self, form):
        saved_cat = form.save()
        # 「保存」
        return redirect('FinDocs:category_index')


class DocTypeDeleteView(DeleteView):
    """削除"""
    model = DocType
    template_name = 'FinDocs/category_del.html'
    context_object_name = 'cat'
    success_url = reverse_lazy('FinDocs:category_index')


#==============================

class ContactListView(ListView):
    """一覧"""
    model = Contact
    template_name = 'FinDocs/contact_index.html'
    context_object_name = 'cons'
    strict = False

    # クエリセット
    def get_queryset(self):
        context = Contact.objects.all().order_by('priority') # 一覧（全件）
        return context


class ContactCreateView(CreateView):
    """追加"""
    model = Contact
    form_class = ContactForm
    template_name = 'FinDocs/contact_add.html'
    context_object_name = 'con'
    success_url = reverse_lazy('FinDocs:contact_index')

    def form_valid(self, form):
        saved_cat = form.save()
        # 「保存」
        return redirect('FinDocs:contact_index')


class ContactEditView(UpdateView):
    """編集"""
    model = Contact
    form_class = ContactForm
    template_name = 'FinDocs/contact_edit.html'
    context_object_name = 'con'
    success_url = reverse_lazy('FinDocs:contact_index')

    def form_valid(self, form):
        saved_cat = form.save()
        # 「保存」
        return redirect('FinDocs:contact_index')


class ContactDeleteView(DeleteView):
    """削除"""
    model = Contact
    template_name = 'FinDocs/contact_del.html'
    context_object_name = 'con'
    success_url = reverse_lazy('FinDocs:contact_index')


#==============================

class OriginalDocPlaceListView(ListView):
    """一覧"""
    model = OriginalDocPlace
    template_name = 'FinDocs/docplace_index.html'
    context_object_name = 'plcs'
    strict = False

    # クエリセット
    def get_queryset(self):
        context = OriginalDocPlace.objects.all().order_by('priority') # 一覧（全件）
        return context


class OriginalDocPlaceCreateView(CreateView):
    """追加"""
    model = OriginalDocPlace
    form_class = OriginalDocPlaceForm
    template_name = 'FinDocs/docplace_add.html'
    context_object_name = 'plc'
    success_url = reverse_lazy('FinDocs:docplace_index')

    def form_valid(self, form):
        saved_cat = form.save()
        # 「保存」
        return redirect('FinDocs:docplace_index')


class OriginalDocPlaceEditView(UpdateView):
    """編集"""
    model = OriginalDocPlace
    form_class = OriginalDocPlaceForm
    template_name = 'FinDocs/docplace_edit.html'
    context_object_name = 'plc'
    success_url = reverse_lazy('FinDocs:docplace_index')

    def form_valid(self, form):
        saved_cat = form.save()
        # 「保存」
        return redirect('FinDocs:docplace_index')


class OriginalDocPlaceDeleteView(DeleteView):
    """削除"""
    model = OriginalDocPlace
    template_name = 'FinDocs/docplace_del.html'
    context_object_name = 'plc'
    success_url = reverse_lazy('FinDocs:docplace_index')

#==============================

def repair_date_format(text):
    reg = re.compile('^([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})')
    m = reg.search(text)
    if m:
        text = "%04d-%02d-%02d" % (int(m.group(1)), int(m.group(2)), int(m.group(3)))
    return text


def check_created_at(now, query):
    T = now.strftime("%Y-%m-%d")
    q = repair_date_format(query)
    t = timezone.datetime.strptime(q, "%Y-%m-%d")
    if t < now:
        T = q
    return T


class DataImport(FormView):
    """インポート"""
    template_name = 'FinDocs/import.html'
    success_url = reverse_lazy('FinDocs:index')
    form_class = DocUploadForm

    def form_valid(self, form):

FinDocs/templates/FinDocs/category_form.html
<form method="POST" id="save">
  {% csrf_token %}
  <table class="table table-bordered">
    <thead class="thead-dark">
      <tr><th scope="col">項目</th><th>入力フォーム</th><th>補足</th></tr>
    </thead>
    <tbody>
      <tr><th scope="col">カテゴリー名</th><td>{{ form.name }}</td><td><span class="small text-danger">必須</span></td></tr>
      <tr><th scope="col">優先度</th><td>{{ form.priority }}</td><td><span class="small text-muted">0以上の数字<br>小さい数字ほど上位に表示される</span></td></tr>
      <tr><th scope="col">備考</th><td>{{ form.remarks }}</td><td></td></tr>
    </tbody>
  </table>
</form>

FinDocs/templates/FinDocs/category_index.html
{% extends "base.html" %}

{% block app_navi_item %}
{% include "FinDocs/admin_menu.html" %}
{% endblock %}

{% block content %}
<div class="row border-bottom mt-2">
  <div class="col-md-8 col-lg-8">
    <h1 class="">FinDocs | カテゴリー</h1>
  </div>
</div>

{% if user.is_authenticated %}
<div class="row my-3">
  <div class="col-md-6 col-lg-6">
    <a href="{% url 'FinDocs:index' %}" class="btn btn-secondary">資料検索ページに戻る</a>
  </div>
  <div class="col-md-6 col-lg-6 text-right">
    <a href="{% url 'FinDocs:category_add' %}" class="btn btn-primary" style="width:80px">追加</a>
  </div>
</div>
{% endif %}

<table class="table table-striped table-bordered mt-2">
  <thead class="thead-dark">
    <tr>
      <th scope="col">カテゴリー名</th>
      <th scope="col">優先度</th>
      <th scope="col">備考</th>
    </tr>
  </thead>
  <tbody>
    {% for cat in cats %}
    <tr>
      <td scope="row"><a href="{% url 'FinDocs:category_edit' cat.pk %}">{{ cat.name }}</a></td>
      <td>{{ cat.priority }}</td>
      <td>{{ cat.remarks }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<!-- モーダル・ダイアログ -->
{% include "FinDocs/modal_export.html" %}

{% endblock content %}

FinDocs/templates/FinDocs/contact_edit.html
{% extends "base.html" %}

{% block app_navi_item %}
{% include "FinDocs/admin_menu.html" %}
{% endblock %}

{% block content %}
<div class="row border-bottom mt-2">
  <div class="col-md-8 col-lg-8">
    <h1 class="">FinDocs | 問合せ先 | 編集</h1>
  </div>
</div>

<div class="row my-3">
    <div class="col col-md-12">
        <a href="{% url 'FinDocs:contact_index' %}" class="btn btn-secondary" style="width:80px">戻る</a>
    </div>
</div>

<!-- form -->
<div class="row mt-2">
  <div class="col col-md-12">
    {% include "FinDocs/contact_form.html" %}
  </div>
</div>

<div class="row">
  <div class="col col-md-6">
      <!--- 保存ボタン　--->
      <button type="button" class="btn btn-primary mr-2" data-toggle="modal" data-target="#save-modal" style="width:80px">保存</button>
      <div class="modal fade" id="save-modal" tabindex="-1" role="dialog" aria-labelledby="label1" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="label1">確認</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                このデータを保存しますか？
            </div>
            <div class="modal-footer">
              <form method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary" form="save">保存する</button>
              </form>
              <button type="button" class="btn btn-secondary" data-dismiss="modal">キャンセル</button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col col-md-6 text-right">
      <!--- 削除ボタン　--->
      <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del-modal" style="width:80px">削除</button>
      <div class="modal fade" id="del-modal" tabindex="-1" role="dialog" aria-labelledby="label2" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="label2">確認</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body text-left">
                本当にこのデータを削除しますか？
            </div>
            <div class="modal-footer">
              <form action="{% url 'FinDocs:contact_del' con.pk %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">削除する</button>
              </form>
              <button type="button" class="btn btn-secondary" data-dismiss="modal">キャンセル</button>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>

<!-- モーダル・ダイアログ -->
{% include "FinDocs/modal_export.html" %}

{% endblock content %}

FinDocs/templates/FinDocs/docplace_index.html
{% extends "base.html" %}

{% block app_navi_item %}
{% include "FinDocs/admin_menu.html" %}
{% endblock %}

{% block content %}
<div class="row border-bottom mt-2">
  <div class="col-md-8 col-lg-8">
    <h1 class="">FinDocs | 原本所在</h1>
  </div>
</div>

{% if user.is_authenticated %}
<div class="row my-3">
  <div class="col-md-6 col-lg-6">
    <a href="{% url 'FinDocs:index' %}" class="btn btn-secondary">資料検索ページに戻る</a>
  </div>
  <div class="col-md-6 col-lg-6 text-right">
    <a href="{% url 'FinDocs:docplace_add' %}" class="btn btn-primary" style="width:80px">追加</a>
  </div>
</div>
{% endif %}

<table class="table table-striped table-bordered mt-2">
  <thead class="thead-dark">
    <tr>
      <th scope="col">場所名</th>
      <th scope="col">優先度</th>
      <th scope="col">備考</th>
    </tr>
  </thead>
  <tbody>
    {% for plc in plcs %}
    <tr>
      <td scope="row"><a href="{% url 'FinDocs:docplace_edit' plc.pk %}">{{ plc.place }}</a></td>
      <td>{{ plc.priority }}</td>
      <td>{{ plc.remarks }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<!-- モーダル・ダイアログ -->
{% include "FinDocs/modal_export.html" %}

{% endblock content %}

FinDocs/templates/FinDocs/index.html
{% extends "base.html" %}

{% block app_navi_item %}
{% include "FinDocs/admin_menu.html" %}
{% endblock %}

{% block content %}
<div class="row border-bottom mt-2">
  <div class="col-md-12 col-lg-12">
    <h1 class="">FinDocs</h1>
  </div>
</div>

<!-- form for document filter -->
{% include "FinDocs/doc_filter_form.html" %}

<!-- pagination -->
{% include "FinDocs/doc_pagenation.html" %}

<table class="table table-striped table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col">タイトル</th>
      <th scope="col">カテゴリ</th>
      <th scope="col">作成年月日</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    {% for rec in recs %}
    <tr>
      <td scope="row">
        <a href="" class="detail-modal" data-toggle="modal" data-target="#detail-modal"
            data-id="{{ rec.id }}"
            data-title="{{ rec.title }}"
            data-type="{{ rec.type }}"
            data-content="{{ rec.content }}"
            data-date="{{ rec.date }}"
            data-contact_to="{{ rec.contact_to }}"
            data-get_is_public_display="{{ rec.get_is_public_display }}"
            data-barcode="{{ rec.barcode }}"
            data-original="{{ rec.original }}"
            data-keywords="{{ rec.keywords }}">{{ rec.title }}</a></td>
      <td>{{ rec.type }}</td>
      <td>{{ rec.date }}</td>
      <td>
        <a href="{{ rec.url }}" target="_blank" class="btn btn-outline-success btn-sm">閲覧</a>
        <a href="{% url 'FinDocs:detail' rec.pk %}" class="btn btn-outline-info btn-sm">詳細</a>
        {% if user.is_authenticated %}
        <a href="{% url 'FinDocs:edit' rec.pk %}" class="btn btn-outline-secondary btn-sm">編集</a>
        {% endif %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<!-- モーダル・ダイアログ -->
{% include "FinDocs/modal_export.html" %}
{% include "FinDocs/modal_detail.html" %}

{% endblock content %}

{% block extra_js %}
<script>
$(function() {
  $('.detail-modal').on('click', function () {
     $("#doc_id").text($(this).data("id"));
     $("#doc_title").text($(this).data("title"));
     $("#doc_type").text($(this).data("type"));
     $("#doc_content").text($(this).data("content"));
     $("#doc_date").text($(this).data("date"));
     $("#doc_contact").text($(this).data("contact_to"));
     $("#doc_public").text($(this).data("get_is_public_display"));
     $("#doc_barcode").text($(this).data("barcode"));
     $("#doc_original").text($(this).data("original"));
     $("#doc_keywords").text($(this).data("keywords"));
  });
});

$(function(){
    // 入力値をリセット
    $('button#reset').on('click', function() {
        $('input[type="search"], select[name="c"], select[name="y"]').val("").removeAttr('selected');
    })
});
</script>
{% endblock extra_js %}

FinDocs/templates/FinDocs/modal_del.html
<div class="modal fade" id="del-modal" tabindex="-1" role="dialog" aria-labelledby="label2" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="label2">確認</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-left">
          本当にこのデータを削除しますか？
      </div>
      <div class="modal-footer">
        <form action="{% url 'FinDocs:del' rec.pk %}" method="POST">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger">削除する</button>
        </form>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">キャンセル</button>
      </div>
    </div>
  </div>
</div>